language: python

python:
  - "2.7"
  - "3.7"

dist: trusty

before_install:
  - sudo apt-get install -y libfftw3-dev

addons:
  apt:
    update: true

install: true

script:
  - make all
  - make testall
